// <auto-generated />
using System;
using BankApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BankApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220226202158_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BankApp.Entities.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("AccountTypeId")
                        .HasColumnType("smallint");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<short>("CurrencyId")
                        .HasColumnType("smallint");

                    b.Property<string>("CustomerId")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TransferLimit")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AccountTypeId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("BankApp.Entities.AccountType", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("InterestRate")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AccountTypes");
                });

            modelBuilder.Entity("BankApp.Entities.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("CountryId")
                        .HasColumnType("smallint");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("BankApp.Entities.Card", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("CardTypeId")
                        .HasColumnType("smallint");

                    b.Property<string>("Cvv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TransactionLimit")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("ValidThru")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CardTypeId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("BankApp.Entities.CardOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerId")
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CardOrders");
                });

            modelBuilder.Entity("BankApp.Entities.CardType", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CardTypes");
                });

            modelBuilder.Entity("BankApp.Entities.Country", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Code = "AD",
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = (short)2,
                            Code = "AE",
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = (short)3,
                            Code = "AF",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = (short)4,
                            Code = "AG",
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = (short)5,
                            Code = "AI",
                            Name = "Anguilla"
                        },
                        new
                        {
                            Id = (short)6,
                            Code = "AL",
                            Name = "Albania"
                        },
                        new
                        {
                            Id = (short)7,
                            Code = "AM",
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = (short)8,
                            Code = "AN",
                            Name = "Netherlands Antilles"
                        },
                        new
                        {
                            Id = (short)9,
                            Code = "AO",
                            Name = "Angola"
                        },
                        new
                        {
                            Id = (short)10,
                            Code = "AQ",
                            Name = "Antarctica"
                        },
                        new
                        {
                            Id = (short)11,
                            Code = "AR",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = (short)12,
                            Code = "AS",
                            Name = "American Samoa"
                        },
                        new
                        {
                            Id = (short)13,
                            Code = "AT",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = (short)14,
                            Code = "AU",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = (short)15,
                            Code = "AW",
                            Name = "Aruba"
                        },
                        new
                        {
                            Id = (short)16,
                            Code = "AZ",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = (short)17,
                            Code = "BA",
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = (short)18,
                            Code = "BB",
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = (short)19,
                            Code = "BD",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = (short)20,
                            Code = "BE",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = (short)21,
                            Code = "BF",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = (short)22,
                            Code = "BG",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = (short)23,
                            Code = "BH",
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = (short)24,
                            Code = "BI",
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = (short)25,
                            Code = "BJ",
                            Name = "Benin"
                        },
                        new
                        {
                            Id = (short)26,
                            Code = "BM",
                            Name = "Bermuda"
                        },
                        new
                        {
                            Id = (short)27,
                            Code = "BN",
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = (short)28,
                            Code = "BO",
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = (short)29,
                            Code = "BR",
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = (short)30,
                            Code = "BS",
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = (short)31,
                            Code = "BT",
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = (short)32,
                            Code = "BV",
                            Name = "Bouvet Island"
                        },
                        new
                        {
                            Id = (short)33,
                            Code = "BW",
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = (short)34,
                            Code = "BY",
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = (short)35,
                            Code = "BZ",
                            Name = "Belize"
                        },
                        new
                        {
                            Id = (short)36,
                            Code = "CA",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = (short)37,
                            Code = "CC",
                            Name = "Cocos [Keeling] Islands"
                        },
                        new
                        {
                            Id = (short)38,
                            Code = "CD",
                            Name = "Congo [DRC]"
                        },
                        new
                        {
                            Id = (short)39,
                            Code = "CF",
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = (short)40,
                            Code = "CG",
                            Name = "Congo [Republic]"
                        },
                        new
                        {
                            Id = (short)41,
                            Code = "CH",
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = (short)42,
                            Code = "CI",
                            Name = "Côte d'Ivoire"
                        },
                        new
                        {
                            Id = (short)43,
                            Code = "CK",
                            Name = "Cook Islands"
                        },
                        new
                        {
                            Id = (short)44,
                            Code = "CL",
                            Name = "Chile"
                        },
                        new
                        {
                            Id = (short)45,
                            Code = "CM",
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = (short)46,
                            Code = "CN",
                            Name = "China"
                        },
                        new
                        {
                            Id = (short)47,
                            Code = "CO",
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = (short)48,
                            Code = "CR",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = (short)49,
                            Code = "CU",
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = (short)50,
                            Code = "CV",
                            Name = "Cape Verde"
                        },
                        new
                        {
                            Id = (short)51,
                            Code = "CX",
                            Name = "Christmas Island"
                        },
                        new
                        {
                            Id = (short)52,
                            Code = "CY",
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = (short)53,
                            Code = "CZ",
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = (short)54,
                            Code = "DE",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = (short)55,
                            Code = "DJ",
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = (short)56,
                            Code = "DK",
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = (short)57,
                            Code = "DM",
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = (short)58,
                            Code = "DO",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = (short)59,
                            Code = "DZ",
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = (short)60,
                            Code = "EC",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = (short)61,
                            Code = "EE",
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = (short)62,
                            Code = "EG",
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = (short)63,
                            Code = "EH",
                            Name = "Western Sahara"
                        },
                        new
                        {
                            Id = (short)64,
                            Code = "ER",
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = (short)65,
                            Code = "ES",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = (short)66,
                            Code = "ET",
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = (short)67,
                            Code = "FI",
                            Name = "Finland"
                        },
                        new
                        {
                            Id = (short)68,
                            Code = "FJ",
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = (short)69,
                            Code = "FK",
                            Name = "Falkland Islands [Islas Malvinas]"
                        },
                        new
                        {
                            Id = (short)70,
                            Code = "FM",
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = (short)71,
                            Code = "FO",
                            Name = "Faroe Islands"
                        },
                        new
                        {
                            Id = (short)72,
                            Code = "FR",
                            Name = "France"
                        },
                        new
                        {
                            Id = (short)73,
                            Code = "GA",
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = (short)74,
                            Code = "GB",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = (short)75,
                            Code = "GD",
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = (short)76,
                            Code = "GE",
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = (short)77,
                            Code = "GF",
                            Name = "French Guiana"
                        },
                        new
                        {
                            Id = (short)78,
                            Code = "GG",
                            Name = "Guernsey"
                        },
                        new
                        {
                            Id = (short)79,
                            Code = "GH",
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = (short)80,
                            Code = "GI",
                            Name = "Gibraltar"
                        },
                        new
                        {
                            Id = (short)81,
                            Code = "GL",
                            Name = "Greenland"
                        },
                        new
                        {
                            Id = (short)82,
                            Code = "GM",
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = (short)83,
                            Code = "GN",
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = (short)84,
                            Code = "GP",
                            Name = "Guadeloupe"
                        },
                        new
                        {
                            Id = (short)85,
                            Code = "GQ",
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = (short)86,
                            Code = "GR",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = (short)87,
                            Code = "GS",
                            Name = "South Georgia and the South Sandwich Islands"
                        },
                        new
                        {
                            Id = (short)88,
                            Code = "GT",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = (short)89,
                            Code = "GU",
                            Name = "Guam"
                        },
                        new
                        {
                            Id = (short)90,
                            Code = "GW",
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = (short)91,
                            Code = "GY",
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = (short)92,
                            Code = "GZ",
                            Name = "Gaza Strip"
                        },
                        new
                        {
                            Id = (short)93,
                            Code = "HK",
                            Name = "Hong Kong"
                        },
                        new
                        {
                            Id = (short)94,
                            Code = "HM",
                            Name = "Heard Island and McDonald Islands"
                        },
                        new
                        {
                            Id = (short)95,
                            Code = "HN",
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = (short)96,
                            Code = "HR",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = (short)97,
                            Code = "HT",
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = (short)98,
                            Code = "HU",
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = (short)99,
                            Code = "ID",
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = (short)100,
                            Code = "IE",
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = (short)101,
                            Code = "IL",
                            Name = "Israel"
                        },
                        new
                        {
                            Id = (short)102,
                            Code = "IM",
                            Name = "Isle of Man"
                        },
                        new
                        {
                            Id = (short)103,
                            Code = "IN",
                            Name = "India"
                        },
                        new
                        {
                            Id = (short)104,
                            Code = "IO",
                            Name = "British Indian Ocean Territory"
                        },
                        new
                        {
                            Id = (short)105,
                            Code = "IQ",
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = (short)106,
                            Code = "IR",
                            Name = "Iran"
                        },
                        new
                        {
                            Id = (short)107,
                            Code = "IS",
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = (short)108,
                            Code = "IT",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = (short)109,
                            Code = "JE",
                            Name = "Jersey"
                        },
                        new
                        {
                            Id = (short)110,
                            Code = "JM",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = (short)111,
                            Code = "JO",
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = (short)112,
                            Code = "JP",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = (short)113,
                            Code = "KE",
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = (short)114,
                            Code = "KG",
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = (short)115,
                            Code = "KH",
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = (short)116,
                            Code = "KI",
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = (short)117,
                            Code = "KM",
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = (short)118,
                            Code = "KN",
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = (short)119,
                            Code = "KP",
                            Name = "North Korea"
                        },
                        new
                        {
                            Id = (short)120,
                            Code = "KR",
                            Name = "South Korea"
                        },
                        new
                        {
                            Id = (short)121,
                            Code = "KW",
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = (short)122,
                            Code = "KY",
                            Name = "Cayman Islands"
                        },
                        new
                        {
                            Id = (short)123,
                            Code = "KZ",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = (short)124,
                            Code = "LA",
                            Name = "Laos"
                        },
                        new
                        {
                            Id = (short)125,
                            Code = "LB",
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = (short)126,
                            Code = "LC",
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = (short)127,
                            Code = "LI",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = (short)128,
                            Code = "LK",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = (short)129,
                            Code = "LR",
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = (short)130,
                            Code = "LS",
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = (short)131,
                            Code = "LT",
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = (short)132,
                            Code = "LU",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = (short)133,
                            Code = "LV",
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = (short)134,
                            Code = "LY",
                            Name = "Libya"
                        },
                        new
                        {
                            Id = (short)135,
                            Code = "MA",
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = (short)136,
                            Code = "MC",
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = (short)137,
                            Code = "MD",
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = (short)138,
                            Code = "ME",
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = (short)139,
                            Code = "MG",
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = (short)140,
                            Code = "MH",
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = (short)141,
                            Code = "MK",
                            Name = "Macedonia [FYROM]"
                        },
                        new
                        {
                            Id = (short)142,
                            Code = "ML",
                            Name = "Mali"
                        },
                        new
                        {
                            Id = (short)143,
                            Code = "MM",
                            Name = "Myanmar [Burma]"
                        },
                        new
                        {
                            Id = (short)144,
                            Code = "MN",
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = (short)145,
                            Code = "MO",
                            Name = "Macau"
                        },
                        new
                        {
                            Id = (short)146,
                            Code = "MP",
                            Name = "Northern Mariana Islands"
                        },
                        new
                        {
                            Id = (short)147,
                            Code = "MQ",
                            Name = "Martinique"
                        },
                        new
                        {
                            Id = (short)148,
                            Code = "MR",
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = (short)149,
                            Code = "MS",
                            Name = "Montserrat"
                        },
                        new
                        {
                            Id = (short)150,
                            Code = "MT",
                            Name = "Malta"
                        },
                        new
                        {
                            Id = (short)151,
                            Code = "MU",
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = (short)152,
                            Code = "MV",
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = (short)153,
                            Code = "MW",
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = (short)154,
                            Code = "MX",
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = (short)155,
                            Code = "MY",
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = (short)156,
                            Code = "MZ",
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = (short)157,
                            Code = "NA",
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = (short)158,
                            Code = "NC",
                            Name = "New Caledonia"
                        },
                        new
                        {
                            Id = (short)159,
                            Code = "NE",
                            Name = "Niger"
                        },
                        new
                        {
                            Id = (short)160,
                            Code = "NF",
                            Name = "Norfolk Island"
                        },
                        new
                        {
                            Id = (short)161,
                            Code = "NG",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = (short)162,
                            Code = "NI",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = (short)163,
                            Code = "NL",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = (short)164,
                            Code = "NO",
                            Name = "Norway"
                        },
                        new
                        {
                            Id = (short)165,
                            Code = "NP",
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = (short)166,
                            Code = "NR",
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = (short)167,
                            Code = "NU",
                            Name = "Niue"
                        },
                        new
                        {
                            Id = (short)168,
                            Code = "NZ",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = (short)169,
                            Code = "OM",
                            Name = "Oman"
                        },
                        new
                        {
                            Id = (short)170,
                            Code = "PA",
                            Name = "Panama"
                        },
                        new
                        {
                            Id = (short)171,
                            Code = "PE",
                            Name = "Peru"
                        },
                        new
                        {
                            Id = (short)172,
                            Code = "PF",
                            Name = "French Polynesia"
                        },
                        new
                        {
                            Id = (short)173,
                            Code = "PG",
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = (short)174,
                            Code = "PH",
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = (short)175,
                            Code = "PK",
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = (short)176,
                            Code = "PL",
                            Name = "Poland"
                        },
                        new
                        {
                            Id = (short)177,
                            Code = "PM",
                            Name = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            Id = (short)178,
                            Code = "PN",
                            Name = "Pitcairn Islands"
                        },
                        new
                        {
                            Id = (short)179,
                            Code = "PR",
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Id = (short)180,
                            Code = "PS",
                            Name = "Palestinian Territories"
                        },
                        new
                        {
                            Id = (short)181,
                            Code = "PT",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = (short)182,
                            Code = "PW",
                            Name = "Palau"
                        },
                        new
                        {
                            Id = (short)183,
                            Code = "PY",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = (short)184,
                            Code = "QA",
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = (short)185,
                            Code = "RE",
                            Name = "Réunion"
                        },
                        new
                        {
                            Id = (short)186,
                            Code = "RO",
                            Name = "Romania"
                        },
                        new
                        {
                            Id = (short)187,
                            Code = "RS",
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = (short)188,
                            Code = "RU",
                            Name = "Russia"
                        },
                        new
                        {
                            Id = (short)189,
                            Code = "RW",
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = (short)190,
                            Code = "SA",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = (short)191,
                            Code = "SB",
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = (short)192,
                            Code = "SC",
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = (short)193,
                            Code = "SD",
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = (short)194,
                            Code = "SE",
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = (short)195,
                            Code = "SG",
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = (short)196,
                            Code = "SH",
                            Name = "Saint Helena"
                        },
                        new
                        {
                            Id = (short)197,
                            Code = "SI",
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = (short)198,
                            Code = "SJ",
                            Name = "Svalbard and Jan Mayen"
                        },
                        new
                        {
                            Id = (short)199,
                            Code = "SK",
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = (short)200,
                            Code = "SL",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = (short)201,
                            Code = "SM",
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = (short)202,
                            Code = "SN",
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = (short)203,
                            Code = "SO",
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = (short)204,
                            Code = "SR",
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = (short)205,
                            Code = "ST",
                            Name = "São Tomé and Príncipe"
                        },
                        new
                        {
                            Id = (short)206,
                            Code = "SV",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = (short)207,
                            Code = "SY",
                            Name = "Syria"
                        },
                        new
                        {
                            Id = (short)208,
                            Code = "SZ",
                            Name = "Swaziland"
                        },
                        new
                        {
                            Id = (short)209,
                            Code = "TC",
                            Name = "Turks and Caicos Islands"
                        },
                        new
                        {
                            Id = (short)210,
                            Code = "TD",
                            Name = "Chad"
                        },
                        new
                        {
                            Id = (short)211,
                            Code = "TF",
                            Name = "French Southern Territories"
                        },
                        new
                        {
                            Id = (short)212,
                            Code = "TG",
                            Name = "Togo"
                        },
                        new
                        {
                            Id = (short)213,
                            Code = "TH",
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = (short)214,
                            Code = "TJ",
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = (short)215,
                            Code = "TK",
                            Name = "Tokelau"
                        },
                        new
                        {
                            Id = (short)216,
                            Code = "TL",
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = (short)217,
                            Code = "TM",
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = (short)218,
                            Code = "TN",
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = (short)219,
                            Code = "TO",
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = (short)220,
                            Code = "TR",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = (short)221,
                            Code = "TT",
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = (short)222,
                            Code = "TV",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = (short)223,
                            Code = "TW",
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = (short)224,
                            Code = "TZ",
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = (short)225,
                            Code = "UA",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = (short)226,
                            Code = "UG",
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = (short)227,
                            Code = "UM",
                            Name = "U.S. Minor Outlying Islands"
                        },
                        new
                        {
                            Id = (short)228,
                            Code = "US",
                            Name = "United States"
                        },
                        new
                        {
                            Id = (short)229,
                            Code = "UY",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = (short)230,
                            Code = "UZ",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = (short)231,
                            Code = "VA",
                            Name = "Vatican City"
                        },
                        new
                        {
                            Id = (short)232,
                            Code = "VC",
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = (short)233,
                            Code = "VE",
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = (short)234,
                            Code = "VG",
                            Name = "British Virgin Islands"
                        },
                        new
                        {
                            Id = (short)235,
                            Code = "VI",
                            Name = "U.S. Virgin Islands"
                        },
                        new
                        {
                            Id = (short)236,
                            Code = "VN",
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = (short)237,
                            Code = "VU",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = (short)238,
                            Code = "WF",
                            Name = "Wallis and Futuna"
                        },
                        new
                        {
                            Id = (short)239,
                            Code = "WS",
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = (short)240,
                            Code = "XK",
                            Name = "Kosovo"
                        },
                        new
                        {
                            Id = (short)241,
                            Code = "YE",
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = (short)242,
                            Code = "YT",
                            Name = "Mayotte"
                        },
                        new
                        {
                            Id = (short)243,
                            Code = "ZA",
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = (short)244,
                            Code = "ZM",
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = (short)245,
                            Code = "ZW",
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("BankApp.Entities.Currency", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("BankApp.Entities.Transfer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Executed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFailed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Ordered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReasonFailed")
                        .HasColumnType("text");

                    b.Property<string>("ReceiverAccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("BankApp.Entities.UserTypes.Admin", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = "7a4165b4-0aca-43fb-a390-294781ee377f"
                        });
                });

            modelBuilder.Entity("BankApp.Entities.UserTypes.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "7a4165b4-0aca-43fb-a390-294781ee377f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ca3c27dc-477a-4690-a1f5-e29ddff530c7",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEFyN6db4vPyM8vs7Dr8zl4vXv+2xTRSLcHpLeTaTL08UOZ9iNtyKinIlkIDNuHP5oA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "31e1d912-6736-4545-9828-68e836eee28c",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("BankApp.Entities.UserTypes.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CityOfBirth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FathersName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("BankApp.Entities.UserTypes.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateOfEmployment")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<char>("Gender")
                        .HasColumnType("character(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Salary")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "fa2640a0-0496-4010-bc27-424e0e5c6f78",
                            ConcurrencyStamp = "8af57a38-88b7-41a3-955b-03ce476bbb79",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "a060dd9f-c966-4a38-8413-549d6d831041",
                            ConcurrencyStamp = "6ba2b11e-52cd-42d0-8b9e-43a969262626",
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        },
                        new
                        {
                            Id = "e2800d7b-1974-4182-829a-4c2e7d92d325",
                            ConcurrencyStamp = "282a7a96-582b-40be-a8fa-909d84b3c587",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", null, t => t.ExcludeFromMigrations());
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "7a4165b4-0aca-43fb-a390-294781ee377f",
                            RoleId = "fa2640a0-0496-4010-bc27-424e0e5c6f78"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", null, t => t.ExcludeFromMigrations());
                });

            modelBuilder.Entity("BankApp.Entities.Account", b =>
                {
                    b.HasOne("BankApp.Entities.AccountType", "AccountType")
                        .WithMany()
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankApp.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankApp.Entities.UserTypes.Customer", null)
                        .WithMany("BankAccounts")
                        .HasForeignKey("CustomerId");

                    b.Navigation("AccountType");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("BankApp.Entities.Address", b =>
                {
                    b.HasOne("BankApp.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankApp.Entities.UserTypes.Customer", "Customer")
                        .WithOne("Address")
                        .HasForeignKey("BankApp.Entities.Address", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BankApp.Entities.Card", b =>
                {
                    b.HasOne("BankApp.Entities.CardType", "CardType")
                        .WithMany()
                        .HasForeignKey("CardTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardType");
                });

            modelBuilder.Entity("BankApp.Entities.CardOrder", b =>
                {
                    b.HasOne("BankApp.Entities.UserTypes.Customer", null)
                        .WithMany("BankCardOrders")
                        .HasForeignKey("CustomerId");
                });

            modelBuilder.Entity("BankApp.Entities.Transfer", b =>
                {
                    b.HasOne("BankApp.Entities.Account", null)
                        .WithMany("Transfers")
                        .HasForeignKey("AccountId");
                });

            modelBuilder.Entity("BankApp.Entities.UserTypes.Admin", b =>
                {
                    b.HasOne("BankApp.Entities.UserTypes.AppUser", "AppUser")
                        .WithOne()
                        .HasForeignKey("BankApp.Entities.UserTypes.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("BankApp.Entities.UserTypes.AppUser", b =>
                {
                    b.OwnsMany("BankApp.Entities.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<long>("Id"));

                            b1.Property<string>("AppUserId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime>("Created")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedByIp")
                                .HasColumnType("text");

                            b1.Property<DateTime>("Expires")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ReasonRevoked")
                                .HasColumnType("text");

                            b1.Property<string>("ReplacedByToken")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("Revoked")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("RevokedByIp")
                                .HasColumnType("text");

                            b1.Property<string>("Token")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("AppUserId");

                            b1.ToTable("RefreshTokens");

                            b1.WithOwner()
                                .HasForeignKey("AppUserId");
                        });

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("BankApp.Entities.UserTypes.Customer", b =>
                {
                    b.HasOne("BankApp.Entities.UserTypes.AppUser", "AppUser")
                        .WithOne()
                        .HasForeignKey("BankApp.Entities.UserTypes.Customer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("BankApp.Entities.UserTypes.Employee", b =>
                {
                    b.HasOne("BankApp.Entities.UserTypes.AppUser", "AppUser")
                        .WithOne()
                        .HasForeignKey("BankApp.Entities.UserTypes.Employee", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BankApp.Entities.UserTypes.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BankApp.Entities.UserTypes.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankApp.Entities.UserTypes.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BankApp.Entities.UserTypes.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BankApp.Entities.Account", b =>
                {
                    b.Navigation("Transfers");
                });

            modelBuilder.Entity("BankApp.Entities.UserTypes.Customer", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("BankAccounts");

                    b.Navigation("BankCardOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
